"""add super admin fields

Revision ID: add_super_admin_fields
Revises: extend_user_model
Create Date: 2026-08-23

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_super_admin_fields'
down_revision = 'extend_user_model'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('can_assign_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_assign_admin')
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
