"""extend user model with profile fields

Revision ID: extend_user_model
Revises: 98d0ae9ac12d
Create Date: 2025-01-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'extend_user_model'
down_revision: Union[str, None] = '98d0ae9ac12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 使用批处理模式重建表，以支持 SQLite 的复杂变更
    with op.batch_alter_table('users') as batch_op:
        # 添加用户编号字段
        batch_op.add_column(sa.Column('user_number', sa.Integer(), nullable=True))

        # 添加手机号字段
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

        # 添加用户状态字段
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_cheater', sa.Boolean(), nullable=False, server_default='false'))

        # 添加管理员权限字段
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('can_speak', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('can_manage_posts', sa.Boolean(), nullable=False, server_default='false'))

        # 添加用户个性化字段
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('user_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('username_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

        # 创建索引
        batch_op.create_index('ix_users_user_number', ['user_number'], unique=True)
        batch_op.create_index('ix_users_phone', ['phone'], unique=True)

    # 为现有用户生成 user_number (使用 id 作为默认值)
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id FROM users"))
    user_ids = [row[0] for row in result]

    for user_id in user_ids:
        conn.execute(sa.text("UPDATE users SET user_number = :id WHERE id = :id"), {"id": user_id})

    # 现在让 user_number 变成 NOT NULL
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('user_number', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_user_number', table_name='users')

    # 删除列
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username_color')
    op.drop_column('users', 'user_tag')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'can_manage_posts')
    op.drop_column('users', 'can_manage_users')
    op.drop_column('users', 'can_speak')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_cheater')
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'user_number')

    # ### end Alembic commands ###
