-- ============================================================
-- Jason227 OJ —— Supabase (PostgreSQL) 建表脚本
-- 由 SQLAlchemy ORM 模型生成并按 PostgreSQL 规范整理：
--   * DATETIME -> TIMESTAMPTZ（模型均为 timezone=True）
--   * 自增主键 -> GENERATED BY DEFAULT AS IDENTITY（兼容手动插入历史数据）
--   * JSON -> JSONB（Supabase 推荐，查询/索引更高效）
--   * 补充 updated_at 自动更新触发器
--
-- 使用方法：Supabase Dashboard -> SQL Editor -> 粘贴全部内容并 Run
-- ============================================================

-- updated_at 自动更新函数（所有表共用）
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ===== 表: users =====
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    user_number INTEGER NOT NULL,
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_banned BOOLEAN NOT NULL DEFAULT false,
    is_cheater BOOLEAN NOT NULL DEFAULT false,
    is_super_admin BOOLEAN NOT NULL DEFAULT false,
    is_admin BOOLEAN NOT NULL DEFAULT false,
    can_speak BOOLEAN NOT NULL DEFAULT true,
    can_manage_users BOOLEAN NOT NULL DEFAULT false,
    can_manage_posts BOOLEAN NOT NULL DEFAULT false,
    can_assign_admin BOOLEAN NOT NULL DEFAULT false,
    avatar_url VARCHAR(500),
    user_tag VARCHAR(100),
    username_color VARCHAR(20),
    bio TEXT,
    remark VARCHAR(100),
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ix_users_username ON users (username);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_user_number ON users (user_number);
CREATE UNIQUE INDEX ix_users_phone ON users (phone);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ===== 表: refresh_tokens =====
CREATE TABLE refresh_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);

-- ===== 表: benben =====
CREATE TABLE benben (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    reply_to INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (user_number) REFERENCES users (user_number),
    FOREIGN KEY (reply_to) REFERENCES benben (id)
);

CREATE INDEX ix_benben_user_number ON benben (user_number);
CREATE INDEX ix_benben_reply_to ON benben (reply_to);

CREATE TRIGGER trg_benben_updated_at
    BEFORE UPDATE ON benben
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ===== 表: judgement_logs =====
CREATE TABLE judgement_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER NOT NULL,
    target_user_id INTEGER NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_detail JSONB,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (admin_id) REFERENCES users (id),
    FOREIGN KEY (target_user_id) REFERENCES users (id)
);

CREATE INDEX ix_judgement_logs_admin_id ON judgement_logs (admin_id);
CREATE INDEX ix_judgement_logs_target_user_id ON judgement_logs (target_user_id);
CREATE INDEX ix_judgement_logs_action_type ON judgement_logs (action_type);

CREATE TRIGGER trg_judgement_logs_updated_at
    BEFORE UPDATE ON judgement_logs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 行级安全（RLS）说明：
-- 本项目由 FastAPI 后端使用直连凭据访问数据库（相当于 service_role），
-- 不经过 Supabase 的 anon/public API，因此无需为 anon 角色开放策略。
-- 若你在 Supabase 面板开启了 RLS，直连凭据（postgres）默认不受限制，
-- 业务不受影响；如需通过 Supabase JS SDK 直接读写，再自行补充 policy。
-- ============================================================
